import { Router } from "express";
import checkUser from "../middlewares/CkeckUser.js";
import allowRole from "../middlewares/AllowRole.js";
import upload from "../lib/multerConfig.js";
import { onUserLogin,onManualRegister,getUserProfile,logout,changeAuthImage,profilePicAdded,onCheckIn,onCheckOut,getTodayAttendace,addFaceId,updateEduction,uploadCertificate,deletCertificate,updateCertificateStatus,changePassword,onRemoveOtp,newCompanyRegister,SendOtpsForCompanyReg,verifyMobileOtp,verifyEmailOtp,resendMobileOtp,resendEmailOtp,updateCompanyDetails,getCompanyDetails,employeeSelfRegister } from "../controllers/AuthController.js";
const router=Router();
router.post("/login",onUserLogin);
router.post("/register",checkUser,allowRole("hr"),onManualRegister);
router.post("/employee-register",employeeSelfRegister);
router.get("/profile",checkUser,getUserProfile);
router.post("/logout",checkUser,logout);
router.put("/addfaceid",checkUser,addFaceId);
router.post("/addauthimage",checkUser,upload.single("image"),changeAuthImage);
router.patch("/profile-pic",checkUser,upload.single("profilePic"),profilePicAdded);
router.post("/checkin",checkUser,allowRole("employee","manager"),onCheckIn);
router.put("/checkout",checkUser,allowRole("employee","manager"),onCheckOut);
router.get("/today-attendace",checkUser,getTodayAttendace);
router.patch("/:id/education",checkUser,updateEduction);
router.patch("/:id/upload-certificates",checkUser,upload.array("certificates"),uploadCertificate);
router.patch("/:id/delete-certificate",checkUser,deletCertificate);
router.patch("/certificates/:fileId/status",checkUser,allowRole("hr"),updateCertificateStatus);
router.patch("/change-password/:empId",checkUser,changePassword);
router.patch("/remove-otp",onRemoveOtp);
router.post("/new-company-reg",upload.single("image"),newCompanyRegister);
router.post("/send-otp",SendOtpsForCompanyReg); router.post("/verify-mobile-otp",verifyMobileOtp); router.post("/verify-email-otp",verifyEmailOtp); router.post("/resend-mobile-otp",resendMobileOtp); router.post("/resend-email-otp",resendEmailOtp);
router.post("/update-company-details",checkUser,allowRole("hr"),upload.single("image"),updateCompanyDetails);
router.get("/company-details",checkUser,getCompanyDetails);
export default router;
