import { Router } from "express";
import checkUser from "../middlewares/CkeckUser.js";
import allowRole from "../middlewares/AllowRole.js";
import upload from "../lib/multerConfig.js";
import * as hr from "../controllers/HrController.js";
const router=Router();
router.use(checkUser,allowRole("hr"));
router.post("/uploadpayslip/:userId",upload.single("file"),hr.UploadPayslip);
router.get("/employees",hr.getEmployees);
router.post("/pay-slip",hr.postPlaySlip);
router.get("/pay-slip/:userId/:month",hr.getPlaySlip);
router.get("/monthwise-pay-slip",hr.getNonHRUsersWithPayslip);
router.post("/add-new-employee",hr.addNewEmployee);
router.put("/edit-employee-details/:id",hr.editEmployee);
router.put("/edit-employee-address/:id",hr.editEmployeeAddress);
router.post("/add-employee-emergencycontact/:id",hr.addEmployeeEmergencyContact);
router.get("/attendace-by-date",hr.getAttendaceByDate);
router.get("/leaves/upcoming",hr.getUpcomingLeaves);
router.patch("/leaves",hr.getUpdateLeaves);
router.post("/todo-create",hr.createEmployeTodo); router.get("/todo-all",hr.getAllTodos); router.delete("/todo-task/:id",hr.deleteTodos); router.patch("/todo-task/:id",hr.updateTodos); router.get("/todo-task/without-pagination",hr.getEmployeesWithTasks);
router.get("/departments",hr.getDepartments); router.patch("/setstatus/:id",hr.changeEmployeeActiveStatus);
router.get("/get-time-sheets/:week",hr.getTimeSheetOfEmployees); router.put("/approve-time-sheet",hr.approveTimeSheet);
router.put("/approve-or-reject-payslip/:id",hr.approveOrRejectPayslip);
router.post("/send-payslip-mail/:id/month/:month",upload.single("file"),hr.sendPaySlipViaMail);
router.get("/employee-docs/:id",hr.getDocsOffAllEmployees); router.get("/dashboard-data",hr.getDashBoardData);
router.post("/add-department",hr.addDepartment); router.put("/edit-department/:id",hr.editDepartment); router.delete("/delete-department/:id",hr.deleteDepartment);
export default router;
